### PR TITLE
Improve accuracy of the stopped/running status indicator following a restart

### PR DESCRIPTION
**Pull request by Steve-Mcl**
fixes https://github.com/flowforge/flowforge/issues/941

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
The PR in action...

Code_T1elHlPMBL

**Comment by Steve-Mcl** [comment]
@hardillb 

I am afraid I have not tested this in anything other than localfs (no capability to test k8s and my docker setup is misbehaving)

**Comment by hardillb** [comment]
I'll have a look at this today.

First question, is there any way to clear the timeout's if the project is deleted before they have all expired?

**Comment by Steve-Mcl** [comment]
> First question, is there any way to clear the timeout's if the project is deleted before they have all expired?

Hmmm good question. Needs to be cancel-able.  
I will take another look. 
Feel free to suggest a solution too 🙂

**Review by hardillb — APPROVED** [review]
OK, tested this both in localfs and in k8s and I'm happy to merge.

Have decided that there is no need to cancel the polling on a project delete because it's all in the launcher, which means that when the project is deleted so is the launcher instance.

**Pull request merged**
