### PR TITLE
add runtimeState

### PR DESCRIPTION
**Pull request by sammachin**
Adds the runtimeState to settings.js 
Closes https://github.com/flowforge/flowforge/issues/839

Have tested with 3.0.1 stacks and 2.2.2 stacks,  as expected 2.x ignores the setting fine.

Existing projects would need to update their stack (or have a container restart) in order to pickup the feature.

### CODE REVIEW

**Comment by knolleary** [comment]
My only hesitation to slipping this in to 0.8 is we don't currently have a way to reflect the started/stopped state in the platform UI. And we still have the 'start'/'stop' options in the platform UI that do not correspond to the Node-RED idea of start/stop. So adding this now would increase the potential for confusion in the UI.

When are the stories for sorting out the rest of the project lifecycle UX planned for?

**Comment by sammachin** [comment]
I don't think there's a requirement that this status (or control) *has* to be exposed in the forge UI, keeping it contained to the Node-RED editor for now would be fine. 
Given our recent conversations about having 2 tiers of state anyway we can then later just expose this in the forge UI as a separate activity.
I do take your point that the terminology is potentially confusing but I think the key thing here is that this is `Stop Flows` `Start Flows` not Stop project. Also worth nothing that  none of this has any impact on what the user is charged for, either current or planned models.

In terms of the other changes I think we could get the switch to Active/Suspend in the 1.0 release, subject to the billing API changes not being too complex, That would then just leave another smaller item to expose the stop/start flows in the Forge app as a separate piece probably in 1.1 or 1.2.

If we add this into 0.8 now we are allowing users to get the value from the feature early at the potential cost of slightly more confusing UX, it feels to be like a worthwhile iteration.

**Comment by knolleary** [comment]
You're right there is value exposing this now. Happy for this to go in.

**Comment by knolleary** [comment]
Just to add - this will *not* get applied to the Device Agent. We don't expose the editor in the device agent and have no UX around telling a device to stop the flows running (without remove the snapshot). That's a whole other set of Stories for the future.

**Pull request merged**
